# generated by DipDup 8.2.2

from __future__ import annotations

from typing import Any, Dict, List

from pydantic import BaseModel, ConfigDict


class Content(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    nat: str
    bytes: str | None = None


class Key(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    withdrawal_id: str
    full_amount: str
    ticketer: str
    content: Content
    timestamp: str
    base_withdrawer: str
    payload: str
    l2_caller: str


class Value(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    paid_out: str


class Value1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    cemented: Dict[str, Any]


class Withdrawal(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    key: Key
    value: Value | Value1


class Config(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    xtz_ticketer: str
    smart_rollup: str
    expiration_seconds: str


class FastWithdrawalStorage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    withdrawals: List[Withdrawal]
    config: Config
    metadata: Dict[str, str]
