# generated by DipDup 8.0.0b5

from __future__ import annotations

from pydantic import BaseModel
from pydantic import ConfigDict

from bridge_indexer.types.tezos.forged_tezos_account import ForgedTezosAccount


class WithdrawalPayload(BaseModel):
    model_config: ConfigDict = ConfigDict(
        extra='forbid',
    )
    amount: int
    sender: str
    receiver: ForgedTezosAccount
    withdrawal_id: int
