version: "3.8"

services:
  db:
    image: timescale/timescaledb:latest-pg15
    restart: always
    ports:
      - "127.0.0.1:${POSTGRES_PORT:-5432}:5432"
    environment:
      - POSTGRES_USER=dipdup
      - POSTGRES_DB=dipdup
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-changeme}
#    volumes:
#      - ./deploy/timescaledb/002_init-db.sh:/docker-entrypoint-initdb.d/002_init-db.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dipdup"]
      interval: 10s
      timeout: 5s
      retries: 5
