[tool.poetry]
name = "Tezos to Etherlink Bridge Indexer"
version = "0.1.0"
description = ""
authors = ["Igor Sereda <sereda.igor.s@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.12,<3.13"
dipdup = {git = "https://github.com/ztepler/dipdup.git", rev="b7aab0d84d502fdff99bbb9bd91977aaddddb46d"}
base58 = "^2.1.1"
pytezos = "^3.13.3"
pydantic-settings = "^2.4.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.4"
ruff = "^0.1.15"
ssort = "^0.12.4"
isort = "^5.13.2"
mypy = "^1.8.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
line_length = 140
force_single_line = true
group_by_package = true
ensure_newline_before_comments = true

[tool.black]
line-length = 140
target-version = ['py312']
skip-string-normalization = true

[tool.ruff]
line-length = 140
ignore = ["E501", "B905"]
target-version = "py312"
extend-select = ["B", "C4", "Q"]
flake8-quotes = {inline-quotes = "single", multiline-quotes = "single"}
