spec_version: 3.0
package: bridge_indexer


database:
  kind: postgres
  host: ${POSTGRES_HOST:-db}
  port: ${POSTGRES_PORT:-5432}
  user: ${POSTGRES_USER:-dipdup}
  password: ${POSTGRES_PASSWORD:-changeme}
  database: ${POSTGRES_DB:-dipdup}

hasura:
  url: ${HASURA_URL}
  admin_secret: ${ADMIN_SECRET:-changeme}
  select_limit: ${SELECT_LIMIT:-1000}
  allow_aggregations: true
  rest: true


datasources:
  tzkt:
    kind: tezos.tzkt
    url: ${TZKT_URL}

  metadata:
    kind: tzip_metadata
    network: ${NETWORK}
    url: ${METADATA_URL}

  tezos_node:
    kind: http
    url: ${TEZOS_NODE_URL}

  etherlink_node:
    kind: evm.node
    url: ${ETHERLINK_NODE_URL}
    http:
      batch_size: 900
      ratelimit_rate: 900
      ratelimit_period: 60
      ratelimit_sleep: 10

  etherlink_subsquid:
    kind: evm.subsquid
    url: ${ETHERLINK_SUBSQUID_URL:-~}

  rollup_node:
    kind: http
    url: ${ROLLUP_NODE_URL}
    http:
      retry_count: 2
      retry_sleep: 1.0
      retry_multiplier: 1.0
      connection_timeout: 1
      request_timeout: 4


advanced:
  reindex:
    config_modified: ignore
    schema_modified: exception
    migration: exception

    rollback: ignore

    manual: wipe
