datasources:
  testnet_node:
    kind: evm.node
    url: https://etherlink.dipdup.net/
    ws_url: wss://etherlink.dipdup.net/

  testnet_subsquid:
    kind: evm.subsquid
    url: https://v2.archive.subsquid.io/network/astar-mainnet
    node: testnet_node


contracts:
  kernel_module:
    kind: evm
    address: 0x0000000000000000000000000000000000000000
    typename: kernel_module

  kernel_precompile:
    kind: evm
    address: 0x0000000000000000000000000000000000000040
    typename: kernel_precompile

#  fa12_token:
#    kind: evm
#    address: 0x8554cD57C0C3E5Ab9d1782c9063279fA9bFA4680
#    typename: fa12_token


indexes:
#  token_transfers:
#    kind: evm.subsquid.events
#    datasource: testnet_subsquid
#    node_only: true
##    first_level: 2676
#    handlers:
#      - callback: etherlink.on_transfer
#        contract: fa12_token
#        name: Transfer

  kernel_events:
    kind: evm.subsquid.events
    datasource: testnet_subsquid
    node_only: true
#    first_level: 2676
    handlers:
      - callback: etherlink.on_deposit
        contract: kernel_module
        name: Deposit

      - callback: etherlink.on_withdraw
        contract: kernel_module
        name: Withdrawal


advanced:
  reindex:
    config_modified: wipe
    schema_modified: wipe
