datasources:
  tzkt:
    kind: tezos.tzkt
    url: ${TZKT_URL}

  metadata:
    kind: tzip_metadata
    network: ${NETWORK}
    url: ${METADATA_URL}

  tezos_node:
    kind: http
    url: ${TEZOS_NODE_URL}

  etherlink_node:
    kind: evm.node
    url: ${ETHERLINK_NODE_URL}
    http:
      batch_size: 100
      ratelimit_rate: 900
      ratelimit_period: 60
      ratelimit_sleep: 10

  etherlink_subsquid:
    kind: evm.subsquid
    url: ${ETHERLINK_SUBSQUID_URL:-~}

  rollup_node:
    kind: http
    url: ${ROLLUP_NODE_URL}
    http:
      retry_count: 2
      retry_sleep: 1.0
      retry_multiplier: 1.0
      connection_timeout: 1
      request_timeout: 4

contracts:
  tezos_smart_rollup:
    kind: tezos
    address: ${SMART_ROLLUP_ADDRESS}
    typename: rollup

  tezos_fast_withdrawal_native:
    kind: tezos
    address: ${FAST_WITHDRAWAL_NATIVE_ADDRESS}
    typename: fast_withdrawal

  etherlink_legacy_rollup_kernel:
    kind: evm
    address: '0x0000000000000000000000000000000000000000'
    typename: kernel

  etherlink_rollup_kernel:
    kind: evm
    address: '0xff00000000000000000000000000000000000002'
    typename: kernel

  etherlink_rollup_kernel_native:
    kind: evm
    address: '0x0000000000000000000000000000000000000000'
    typename: kernel_native

  l2_withdrawal_precompile_fa:
    kind: evm
    address: '0xff00000000000000000000000000000000000002'
    typename: kernel

  l2_withdrawal_precompile_native:
    kind: evm
    address: '0xff00000000000000000000000000000000000001'
    typename: kernel_native


  l2_tzbtc_token:
    kind: evm
    address: '0x03e39ff2b379fbcd9284ab457113d82ff4dabbf4'
    typename: l2_token

  l2_sirius_token:
    kind: evm
    address: '0x22565c35ad439cbb8399bfc733c56c9f5a10e3a6'
    typename: l2_token
  
  l2_usdt_token:
    kind: evm
    address: '0x3dff505a2a69e6e0b05fdb71b5f6ddd514fdaf47'
    typename: l2_token

indexes:
  tezos_head:
    kind: tezos.head
    datasources:
      - tzkt
    callback: tezos.on_head

  tezos_rollup_cement:
    kind: tezos.operations
    first_level: ${L1_FIRST_LEVEL}
    datasources:
      - tzkt
    types:
      - sr_cement
    contracts:
      - tezos_smart_rollup
    handlers:
      - callback: tezos.on_cement_commitment
        pattern:
          - type: sr_cement
            destination: tezos_smart_rollup


  tezos_deposit_operations:
    kind: tezos.operations
    first_level: ${L1_FIRST_LEVEL}
    datasources:
      - tzkt
    types:
      - transaction
    contracts:
      - tezos_smart_rollup
    handlers:
      - callback: tezos.on_rollup_call
        pattern:
          - type: transaction
            destination: tezos_smart_rollup
            entrypoint: default


  tezos_claim_fast_withdrawal_operations:
    kind: tezos.operations
    first_level: ${L1_FIRST_LEVEL}
    datasources:
      - tzkt
    types:
      - transaction
    contracts:
      - tezos_fast_withdrawal_native
    handlers:
      - callback: tezos.on_claim_xtz_fast_withdrawal
        pattern:
          - type: transaction
            destination: tezos_fast_withdrawal_native
            entrypoint: payout_withdrawal

  etherlink_deposit_events:
    kind: evm.events
    first_level: ${L2_FIRST_LEVEL}
    datasources:
      - etherlink_subsquid
      - etherlink_node
    handlers:
      - callback: etherlink.on_deposit
        contract: etherlink_rollup_kernel
        name: Deposit

  etherlink_xtz_deposit_transactions:
    kind: evm.transactions
    first_level: ${L2_FIRST_LEVEL}
    datasources:
      - etherlink_subsquid
      - etherlink_node
    handlers:
      - callback: etherlink.on_xtz_deposit
        from_: etherlink_rollup_kernel


  etherlink_withdrawal_events:
    kind: evm.events
    first_level: ${L2_FIRST_LEVEL}
    datasources:
      - etherlink_subsquid
      - etherlink_node
    handlers:
      - callback: etherlink.on_withdraw
        contract: etherlink_rollup_kernel
        name: Withdrawal
      - callback: etherlink.on_xtz_withdraw
        contract: etherlink_rollup_kernel_native
        name: Withdrawal
      - callback: etherlink.on_withdraw
        contract: l2_withdrawal_precompile_fa
        name: Withdrawal
      - callback: etherlink.on_xtz_withdraw
        contract: l2_withdrawal_precompile_native
        name: Withdrawal
      - callback: etherlink.on_xtz_withdraw
        contract: l2_withdrawal_precompile_native
        name: FastWithdrawal

  tezos_withdrawal_operations:
    kind: tezos.operations
    first_level: ${L1_FIRST_LEVEL}
    datasources:
      - tzkt
    types:
      - sr_execute
    contracts:
      - tezos_smart_rollup
      - tezos_fast_withdrawal_native
    handlers:
      - callback: tezos.on_rollup_execute
        pattern:
          - type: sr_execute
            destination: tezos_smart_rollup
      - callback: tezos.on_rollup_execute
        pattern:
          - type: sr_execute
            destination: tezos_fast_withdrawal_native


  etherlink_token_balance_update_events:
    kind: evm.events
    datasources:
      - etherlink_subsquid
      - etherlink_node
    handlers:
      - callback: etherlink.on_transfer
        contract: l2_tzbtc_token
        name: Transfer
      - callback: etherlink.on_transfer
        contract: l2_sirius_token
        name: Transfer
      - callback: etherlink.on_transfer
        contract: l2_usdt_token
        name: Transfer
