datasources:
  tzkt:
    kind: tezos.tzkt
    url: ${TZKT_URL}

  metadata:
    kind: tzip_metadata
    network: ${NETWORK}
    url: ${METADATA_URL}

  tezos_node:
    kind: http
    url: ${TEZOS_NODE_URL}

  etherlink_node:
    kind: evm.node
    url: ${ETHERLINK_NODE_URL}

  rollup_node:
    kind: http
    url: ${ROLLUP_NODE_URL}
    http:
      retry_count: 2
      retry_sleep: 1.0
      retry_multiplier: 1.0
      connection_timeout: 1
      request_timeout: 4

contracts:
  tezos_smart_rollup:
    kind: tezos
    address: ${SMART_ROLLUP_ADDRESS}
    typename: rollup

  etherlink_rollup_kernel:
    kind: evm
    address: '0x0000000000000000000000000000000000000000'
    typename: kernel

  etherlink_rollup_kernel_native:
    kind: evm
    address: '0x0000000000000000000000000000000000000000'
    typename: kernel_native

  l2_withdrawal_precompile_fa:
    kind: evm
    address: '0xff00000000000000000000000000000000000002'
    typename: kernel

  l2_withdrawal_precompile_native:
    kind: evm
    address: '0xff00000000000000000000000000000000000001'
    typename: kernel_native

indexes:
  tezos_head:
    kind: tezos.head
    datasources:
      - tzkt
    callback: tezos.on_head

  tezos_rollup_cement:
    kind: tezos.operations
    first_level: ${L1_FIRST_LEVEL}
    datasources:
      - tzkt
    types:
      - sr_cement
    contracts:
      - tezos_smart_rollup
    handlers:
      - callback: tezos.on_cement_commitment
        pattern:
          - type: sr_cement
            destination: tezos_smart_rollup


  tezos_deposit_operations:
    kind: tezos.operations
    first_level: ${L1_FIRST_LEVEL}
    datasources:
      - tzkt
    types:
      - transaction
    contracts:
      - tezos_smart_rollup
    handlers:
      - callback: tezos.on_rollup_call
        pattern:
          - type: transaction
            destination: tezos_smart_rollup
            entrypoint: default


  etherlink_deposit_events:
    kind: evm.events
    first_level: ${L2_FIRST_LEVEL}
    datasources:
      - etherlink_node
    handlers:
      - callback: etherlink.on_deposit
        contract: etherlink_rollup_kernel
        name: Deposit
      - callback: etherlink.on_deposit
        contract: l2_withdrawal_precompile_fa
        name: Deposit

  etherlink_xtz_deposit_transactions:
    kind: evm.transactions
    first_level: ${L2_FIRST_LEVEL}
    datasources:
      - etherlink_node
    handlers:
      - callback: etherlink.on_xtz_deposit
        from_: etherlink_rollup_kernel


  etherlink_withdrawal_events:
    kind: evm.events
    first_level: ${L2_FIRST_LEVEL}
    datasources:
      - etherlink_node
    handlers:
      - callback: etherlink.on_withdraw
        contract: etherlink_rollup_kernel
        name: Withdrawal
      - callback: etherlink.on_xtz_withdraw
        contract: etherlink_rollup_kernel_native
        name: Withdrawal
      - callback: etherlink.on_withdraw
        contract: l2_withdrawal_precompile_fa
        name: Withdrawal
      - callback: etherlink.on_xtz_withdraw
        contract: l2_withdrawal_precompile_native
        name: Withdrawal

  tezos_withdrawal_operations:
    kind: tezos.operations
    first_level: ${L1_FIRST_LEVEL}
    datasources:
      - tzkt
    types:
      - sr_execute
    contracts:
      - tezos_smart_rollup
    handlers:
      - callback: tezos.on_rollup_execute
        pattern:
          - type: sr_execute
            destination: tezos_smart_rollup
