# generated by datamodel-codegen:
#   filename:  withdraw.json

from __future__ import annotations

from pydantic import BaseModel
from pydantic import Extra

from bridge_indexer.types.tezos.forged_tezos_account import ForgedTezosAccount


class TicketContent(BaseModel):
    class Config:
        extra = Extra.forbid

    ticket_id: int
    metadata: bytes | None


class Ticket(BaseModel):
    class Config:
        extra = Extra.forbid

    ticketer: ForgedTezosAccount
    content: TicketContent
    amount: int


class WithdrawParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    receiver: ForgedTezosAccount
    ticket: Ticket
