# generated by datamodel-codegen:
#   filename:  withdraw.json

from typing import Literal

from pydantic import BaseModel

from bridge_indexer.types.tezos.forged_tezos_account import ForgedTezosAccount


class TicketContent(BaseModel):
    class Config:
        forbid: Literal['forbid'] = 'forbid'

    ticket_id: int
    metadata: bytes | None


class Ticket(BaseModel):
    class Config:
        forbid: Literal['forbid'] = 'forbid'

    ticketer: ForgedTezosAccount
    content: TicketContent
    amount: int


class WithdrawParameter(BaseModel):
    class Config:
        forbid: Literal['forbid'] = 'forbid'

    receiver: ForgedTezosAccount
    ticket: Ticket
