# generated by DipDup 8.0.0b5

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel


class DepositPayload(BaseModel):
    class Config:
        forbid: Literal['forbid'] = 'forbid'

    ticket_hash: int
    ticket_owner: str
    receiver: str
    amount: int
    inbox_level: int
    inbox_msg_id: int
