# generated by DipDup 8.0.0b3

from __future__ import annotations

from pydantic import BaseModel
from pydantic import ConfigDict

from bridge_indexer.types.tezos.forged_tezos_account import ForgedTezosAccount


class WithdrawalPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ticket_hash: int
    sender: str
    ticket_owner: str
    receiver: ForgedTezosAccount
    proxy: ForgedTezosAccount
    amount: int
    withdrawal_id: int
