# generated by datamodel-codegen:
#   filename:  tezos_storage.json

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel


class Content(BaseModel):
    class Config:
        forbid: Literal['forbid'] = 'forbid'

    nat: str
    bytes: str | None


class Token(BaseModel):
    class Config:
        forbid: Literal['forbid'] = 'forbid'

    fa12: str


class Fa2(BaseModel):
    class Config:
        forbid: Literal['forbid'] = 'forbid'

    address: str
    nat: str


class Token1(BaseModel):
    class Config:
        forbid: Literal['forbid'] = 'forbid'

    fa2: Fa2


class TicketerStorage(BaseModel):
    class Config:
        forbid: Literal['forbid'] = 'forbid'

    content: Content
    metadata: dict[str, str]
    token: Token | Token1
